//
// Created by evleaps on 09.10.17.
//

#ifndef LOBACHEVSKYUNIVERSITY_HOMEWORK_EUCLIDEANTEST_H
#define LOBACHEVSKYUNIVERSITY_HOMEWORK_EUCLIDEANTEST_H

void testEuclidean();

#endif //LOBACHEVSKYUNIVERSITY_HOMEWORK_EUCLIDEANTEST_H
