//
// Created by evleaps on 06.10.17.
//

#ifndef LOBACHEVSKYUNIVERSITY_HOMEWORK_SEARCHSQUAREINCIRCLE_H
#define LOBACHEVSKYUNIVERSITY_HOMEWORK_SEARCHSQUAREINCIRCLE_H

void searchSquareInCircle();

#endif //LOBACHEVSKYUNIVERSITY_HOMEWORK_SEARCHSQUAREINCIRCLE_H



