//
// Created by evleaps on 06.10.17.
//
#ifndef LOBACHEVSKYUNIVERSITY_HOMEWORK_EUCLIDEANALGORITHM_H
#define LOBACHEVSKYUNIVERSITY_HOMEWORK_EUCLIDEANALGORITHM_H

void CoefficientBezu();

#endif //LOBACHEVSKYUNIVERSITY_HOMEWORK_EUCLIDEANALGORITHM_H
